---
# install_omeka.yml
- hosts: local
  become: yes
  become_method: sudo


  roles:
  - { role: geerlingguy.ntp }
  - { role: geerlingguy.mysql }
  - { role: franklinkim.openssl }
  - { role: geerlingguy.apache }
  - { role: geerlingguy.php }
  - { role: geerlingguy.apache-php-fpm }
  - { role: geerlingguy.php-mysql }
#  - { role: zerohacks.imagemagick }
  - { role: install_ImageMagick }
  - { role: arc-install-omeka, tags: ['omeka'] }

