---
- src: geerlingguy.ntp
- src: geerlingguy.mysql
- src: franklinkim.openssl
- src: geerlingguy.apache
- src: geerlingguy.php
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.php-mysql
- src: zerohacks.imagemagick

