---

- name: Install ImageMagick on centos
  become: yes
  become_user: root
  yum:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ centos_packages }}"
  when: ansible_os_family  == "RedHat"

- name: Install ImageMagick on Ubuntu
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ ubuntu_packages }}"
  when: ansible_os_family  == "Debian"

- name: Copy policy file for ImageTragic fix on centos
  become: yes
  become_user: root
  copy: src=policy.xml dest=/etc/ImageMagick
  when: ansible_os_family  == "RedHat"

- name: Copy policy file for ImageTragic fix on ubuntu
  become: yes
  become_user: root
  copy: src=policy.xml dest=/etc/ImageMagick-6
  when: ansible_os_family  == "Debian"
